// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIEszCpO2V2SiCVb-mzkH7IFUuDeW93ag',
    appId: '1:295955328549:web:f7a7884285414784b799cc',
    messagingSenderId: '295955328549',
    projectId: 'chatapp-8db27',
    authDomain: 'chatapp-8db27.firebaseapp.com',
    storageBucket: 'chatapp-8db27.firebasestorage.app',
    measurementId: 'G-DJ2SKWVBRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3KCOzoT5lNvgPc2507bd2-uRAxxVyOo',
    appId: '1:295955328549:android:e800ab16e4b71fc1b799cc',
    messagingSenderId: '295955328549',
    projectId: 'chatapp-8db27',
    storageBucket: 'chatapp-8db27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OP3Yy5fHFyR7TioRCVaDNXHUMAOzhBE',
    appId: '1:295955328549:ios:62be1f5afbe5350ab799cc',
    messagingSenderId: '295955328549',
    projectId: 'chatapp-8db27',
    storageBucket: 'chatapp-8db27.firebasestorage.app',
    iosBundleId: 'com.example.sabak23ChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OP3Yy5fHFyR7TioRCVaDNXHUMAOzhBE',
    appId: '1:295955328549:ios:62be1f5afbe5350ab799cc',
    messagingSenderId: '295955328549',
    projectId: 'chatapp-8db27',
    storageBucket: 'chatapp-8db27.firebasestorage.app',
    iosBundleId: 'com.example.sabak23ChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIEszCpO2V2SiCVb-mzkH7IFUuDeW93ag',
    appId: '1:295955328549:web:e4fad88e7a7d3513b799cc',
    messagingSenderId: '295955328549',
    projectId: 'chatapp-8db27',
    authDomain: 'chatapp-8db27.firebaseapp.com',
    storageBucket: 'chatapp-8db27.firebasestorage.app',
    measurementId: 'G-Q5PCH1WRXM',
  );
}
