// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaAGPyoMR1CyMA47ZTExniPFGKO8zwmVU',
    appId: '1:222643831077:web:483502818707582b4e5acc',
    messagingSenderId: '222643831077',
    projectId: 'dome-1b340',
    authDomain: 'dome-1b340.firebaseapp.com',
    storageBucket: 'dome-1b340.firebasestorage.app',
    measurementId: 'G-VFVNEG9NTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMnhkeZ4JDBQQZyXhCu6GD28XwvjPbglY',
    appId: '1:222643831077:android:f9c71aa820cca8ca4e5acc',
    messagingSenderId: '222643831077',
    projectId: 'dome-1b340',
    storageBucket: 'dome-1b340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUh9wBJcrNfIHjWYBmHLm_Ab89jMMbqGw',
    appId: '1:222643831077:ios:686fb888245e99174e5acc',
    messagingSenderId: '222643831077',
    projectId: 'dome-1b340',
    storageBucket: 'dome-1b340.firebasestorage.app',
    iosBundleId: 'com.example.sabak21FirebaseAdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUh9wBJcrNfIHjWYBmHLm_Ab89jMMbqGw',
    appId: '1:222643831077:ios:686fb888245e99174e5acc',
    messagingSenderId: '222643831077',
    projectId: 'dome-1b340',
    storageBucket: 'dome-1b340.firebasestorage.app',
    iosBundleId: 'com.example.sabak21FirebaseAdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaAGPyoMR1CyMA47ZTExniPFGKO8zwmVU',
    appId: '1:222643831077:web:549cc0799fccc8e84e5acc',
    messagingSenderId: '222643831077',
    projectId: 'dome-1b340',
    authDomain: 'dome-1b340.firebaseapp.com',
    storageBucket: 'dome-1b340.firebasestorage.app',
    measurementId: 'G-9NH5D057LK',
  );
}
