// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVHhzEQHVKtzMgNnwZGw0HP67iG0ly5sY',
    appId: '1:755629725483:web:f5548ad47c58c383d2576e',
    messagingSenderId: '755629725483',
    projectId: 'mydb-57d59',
    authDomain: 'mydb-57d59.firebaseapp.com',
    storageBucket: 'mydb-57d59.firebasestorage.app',
    measurementId: 'G-28F09J9T60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdyq2tBobNf9ILbXTHisTrTVOdAq4Glh8',
    appId: '1:755629725483:android:8645ffc99b6314a7d2576e',
    messagingSenderId: '755629725483',
    projectId: 'mydb-57d59',
    storageBucket: 'mydb-57d59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyscS54amCgXgjF1kYxCd_AJhcPl0CFaA',
    appId: '1:755629725483:ios:ba4f62ee672133ebd2576e',
    messagingSenderId: '755629725483',
    projectId: 'mydb-57d59',
    storageBucket: 'mydb-57d59.firebasestorage.app',
    iosBundleId: 'com.example.sabak22FirebaseWithData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyscS54amCgXgjF1kYxCd_AJhcPl0CFaA',
    appId: '1:755629725483:ios:ba4f62ee672133ebd2576e',
    messagingSenderId: '755629725483',
    projectId: 'mydb-57d59',
    storageBucket: 'mydb-57d59.firebasestorage.app',
    iosBundleId: 'com.example.sabak22FirebaseWithData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVHhzEQHVKtzMgNnwZGw0HP67iG0ly5sY',
    appId: '1:755629725483:web:a8143ab1bc075e34d2576e',
    messagingSenderId: '755629725483',
    projectId: 'mydb-57d59',
    authDomain: 'mydb-57d59.firebaseapp.com',
    storageBucket: 'mydb-57d59.firebasestorage.app',
    measurementId: 'G-GZH1LMLHR9',
  );
}
